uwblueprint/starter-code

.gitignore, backend/wsgi.py, wsgi.py
=> Move wsgi to root directory

backend/routes.py, backend/server.py
=> Create basic flask blueprint

docs/SETUP.md
=> Project setup documentation

Pipfile, Pipfile.lock, backend/routes.py, backend/server.py, docs/DEVELOPMENT.md, docs/SETUP.md
=> Add yapf linter

backend/db/client.py
=> Add simple query function

backend/db/client.py, backend/routes.py
=> Added endpoint to retrieve data from db

docs/PULL_REQUEST_TEMPLATE.md
=> Update pull req template

docs/CREATING_A_PROJECT.md, docs/SETUP.md
=> Updated doc creating a project

.env, .gitignore, backend/__init__.py, backend/db/client.py, backend/db/init_db.py, backend/routes.py, scripts/setup_postgres.sh
=> Refactors to backend code

docs/CREATING_A_PROJECT.md
=> Added Py Flask Postgres docs to creating a project

package-lock.json, package.json, src/actions/index.js, src/actions/simpleAction.js, src/index.js, src/reducers/index.js, src/reducers/simpleReducer.js, src/store.js, src/types/index.js, src/types/simpleType.js
=> redux boilerplate

README.md
@loicmurumba is the hero we need but not the one we deserve
=> Link setup instructions for windows

package-lock.json, package.json, src/components/Title.js
=> Add initial onClick GET request to flask backend

Pipfile, Pipfile.lock
=> Added psycopg to pipenv deps

.env, .gitignore, backend/db/init_db.py, backend/recycled_material.py, docs/SETUP.md
=> Make Firebase work with flask and update docs for Firebase setup

package-lock.json, package.json, src/components/Display.js, src/index.js
=> add firebase support

docs/WINDOWS_SETUP.md
Not exhaustive, but I think it's a good start
=> Start windows documentation

docs/WINDOWS_SETUP.md, package-lock.json, package.json, src/components/Display.js, src/index.js
=> Reset master

backend/db/init_db.py, backend/init_firestore_db.py, docs/SETUP.md
=> Move Firebase setup out of init_db.py

test.txt
Trivial change to test post-merge Git hook.
=> Add test.txt (post-merge Git hook test 1)

test.txt
Trivial change to test post-merge Git hook.
=> Update test.txt (post-merge Git hook test 2)
